### ISSUE TITLE
Update MFCMapi

### ISSUE THREAD

**Issue by FranklinYu** [bill-long/chocolatey-packages#2]
Please also update the package information.

Latest version: 19.0.19115.01
Homepage: https://stephenegriffin.github.io/mfcmapi/
Software source: https://github.com/stephenegriffin/mfcmapi

**Comment by bill-long** [comment]
If anyone wants to take of maintenance of this package, please let me know.

**Comment by FranklinYu** [comment]
New package is published. Thank you for your maintenance in the past! :)
